### ISSUE TITLE
`insert_table` can't handle non 200 responses

### ISSUE THREAD

**Issue by couralex6** [duneanalytics/dune-client#128]
The `InsertTableResult` [object](https://github.com/duneanalytics/dune-client/blob/main/dune_client/models.py#L372-L377) only has one field (`rows_written`) which is only found in the 200 response:
```
{
  "rows_written": 9000,
  "bytes_written": 90
}
```

Codes 400, 401, 404, and 500 each have the following response schema:
```
{
  "error": "some error message"
}
```

When an insert error occurs, the client crashes and throws the error: `KeyError: 'rows_written'` without actually revealing the error returned by the API. This is making it hard to debug and to handle errors.

**Comment by bh2smith** [comment]
Closed by #129 - let me know if you need a new release immediately, or if it can just linger till the next improvement.
